[general]
# Import additional configuration files
import = ["/home/rlc/.cache/wal/colors-alacritty.toml"]

# Shell configuration
#shell = { program = "/bin/bash", args = [] }

[window]
opacity = 0.4
decorations = "none"
blur = true
padding = { x = 5, y = 5 }

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
size = 12.0
